name: fcp-sfd-comms
services:
  fcp-sfd-comms-publisher-stub:
    ports:
      - '3008:3008'
      - '9008:9229'
    networks:
      - fcp-sfd

  localstack-2:
    ports:
      - '4568:4568'
      - '4600-4649:4600-4649'
    volumes:
      - ./localstack/localstack.sh:/etc/localstack/init/ready.d/localstack.sh
      - localstack-2-data:/var/lib/localstack
    networks:
      - fcp-sfd

volumes:
  localstack-2-data:

networks:
  fcp-sfd:
    driver: bridge
    name: fcp-sfd
