name: fcp-sfd-comms-publisher-stub

services:
  fcp-sfd-comms-publisher-stub:
    ports:
      - '3008:3008'
    networks:
      - fcp-sfd

  localstack:
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    volumes:
      - ./localstack/localstack.sh:/etc/localstack/init/ready.d/localstack.sh
      - localstack-data:/var/lib/localstack
    networks:
      - fcp-sfd

volumes:
  localstack-data:

networks:
  fcp-sfd:
    driver: bridge
    name: fcp-sfd
